services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge